# Generated by Django 2.1.1 on 2018-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180918_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojo',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
