# Generated by Django 2.1.1 on 2018-09-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180918_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_liked',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user_upload',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='dojo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Dojo',
        ),
        migrations.DeleteModel(
            name='Ninja',
        ),
    ]
